<section>
  <header class="text-center">
    <h3> <?=  ViewHelpers::imageTag('black_logo.png', 'class="painel"'); ?> Provweb <small> Usuários</small </h3>
    </header>
  </section>

  <section>
    <table class="table table-hover table-bordered text-center">
      <thead >
        <tr >
          <th class="text-center">ID <i class="fa fa-sort-desc"></i></th>
          <th class="text-center">Nome</th>
          <th class="text-center">Email</th>
          <th class="text-center">Data do Registro</th>
        </tr>
      </thead>
      <tbody>
        <?php
        $users = User::all();
        foreach ($users as $user): ?>
        <tr>
          <td><?= $user->getId(); ?></td>
          <td><?= $user->getName(); ?></td>
          <td><?= $user->getEmail(); ?></td>
          <td><?= ViewHelpers::dateFormat($user->getCreatedAt()); ?></td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
  </section>
