<div class="row">
  <div class="col-md-3">
    <div class="form-group input-group <?= $this->client->getErrors('cpf') ? 'has-error' : '' ?>">
      <span class="input-group-addon">CPF</span>
      <input type="text" class="form-control" name="client[cpf]" value="<?= $this->client->getcpf() ?>" id="client_cpf">
    </div>
    <p class="help-block"><?= $this->client->getErrors('cpf') ?></p>
  </div>

  <div class="col-md-4">
    <div class="form-group input-group <?= $this->client->getErrors('date_of_birth') ? 'has-error' : '' ?>">
      <span class="input-group-addon">Data de Nascimento</span>
      <input type="date" class="form-control" name="client[date_of_birth]" value="<?= $this->client->getDateofBirth() ?>" id="client_date_of_birth">
    </div>
    <p class="help-block"><?= $this->client->getErrors('date_of_birth') ?></p>
  </div>
</div>
