<div class="row">
  <div class="col-md-8">
    <div class="form-group input-group">
      <span class="input-group-addon"> Nome Completo</span>
      <input disabled type="text" class="form-control" name="client[name]" value="<?= $this->order->getClient()->getName() ?>" id="client_name" autofocus>
    </div>
  </div>

  <div class="col-md-4">
    <div class="form-group input-group">
      <span class="input-group-addon"> Cidade</span>
      <select disabled class="form-control" name="client[id_city]" id="client_city">
        <option value="">Cidade </option>
        <?php foreach ($this->cities as $city): ?>
          <option value='<?= $city->getId() ?>' <?= ($city->getid() === $this->order->getClient()->getCityId()) ? 'selected' : '' ?> >
            <?= $city->getName() ?>
          </option>
          <?php endForeach; ?>
        </select>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group input-group">
        <span class="input-group-addon">Endereço</span>
        <input disabled type="text" class="form-control" name="client[address]" value="<?= $this->order->getClient()->getAddress() ?>" id="client_address">
      </div>
    </div>

    <div class="col-md-2">
      <div class="form-group input-group">
        <span class="input-group-addon">Número</span>
        <input disabled type="text" class="form-control" name="client[address_number]" value="<?= $this->order->getClient()->getAddressNumber() ?>" id="client_address_number">
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group input-group">
        <span class="input-group-addon">Bairro</span>
        <input disabled type="text" class="form-control" name="client[district]" value="<?= $this->order->getClient()->getDistrict() ?>" id="client_district">
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group input-group ">
        <span class="input-group-addon">CEP</span>
        <input disabled type="text" class="form-control" name="client[address_cep]" value="<?= $this->order->getClient()->getAddressCep() ?>" id="client_address_cep">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group input-group ">
        <span class="input-group-addon">Telefone</span>
        <input disabled type="text" class="form-control" name="client[phone]" value="<?= $this->order->getClient()->getPhone() ?>" id="client_phone">
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group input-group">
        <span class="input-group-addon">Email</span>
        <input disabled type="text" class="form-control" name="client[email]" value="<?= $this->order->getClient()->getEmail() ?>" id="client_email">
      </div>
    </div>
  </div>
