<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <?= ViewHelpers::linkTo('/', ViewHelpers::imageTag('black_logo.png', 'class="navbar-brand"')) ?>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--  SE ESTIVER LOGADO -->
      <?php if (SessionHelpers::isLoggedIn()): ?>
        <ul class="nav navbar-nav navbar-left ">

          <!--  CADASTROS -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-th-list"></i> Cadastros</a>
            <ul class="dropdown-menu" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
              <li class="<?= ViewHelpers::activeClass('/clientes') ?>">
                <?= ViewHelpers::linkTo('/clientes', '<i class="fa fa-users"></i> Clientes') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/produtos') ?>">
                <?= ViewHelpers::linkTo('/produtos', '<i class="fa fa-shopping-basket"></i> Produtos') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/categorias') ?>">
                <?= ViewHelpers::linkTo('/categorias', '<i class="fa fa-tags"></i> Categorias') ?>
              </li>
            </ul>
          </li>

          <!--  PEDIDOS -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-shopping-cart"></i> Pedidos</a>
            <ul class="dropdown-menu" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
              <li>
                <?= ViewHelpers::linkTo('/clientes', '<i class="fa fa-plus"></i> Novo') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/pedidos') ?>">
                <?= ViewHelpers::linkTo('/pedidos', '<i class="fa fa-search"></i> Informações') ?>
              </li>
            </ul>
          </li>

          <!--  RELATÓRIOS -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-line-chart"></i> Relatórios</a>
            <ul class="dropdown-menu" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
              <li class="<?= ViewHelpers::activeClass('/relatorios/ranking-de-vendas') ?>">
                <?= ViewHelpers::linkTo('/relatorios/ranking-de-vendas', '<i class="fa fa-trophy"></i> Ranking de Vendas') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/relatorios/balanco-de-vendas') ?>">
                <?= ViewHelpers::linkTo('/relatorios/balanco-de-vendas', '<i class="fa fa-area-chart"></i> Balanço de Vendas') ?>
              </li>
            </ul>
          </li>
        </ul>
        <!--  CONFIGURAÇÕES -->
        <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text"><?= $this->currentUser()->getName() ?></p>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog"></i></a>
            <ul class="dropdown-menu" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
              <li class="<?= ViewHelpers::activeClass('/perfil') ?>">
                <?= ViewHelpers::linkTo('/perfil', '<i class="fa fa-user"></i> Editar Perfil') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/criar-conta') ?>">
                <?= ViewHelpers::linkTo('/criar-conta', '<i class="fa fa-user-plus"></i> Criar Conta') ?>
              </li>
              <li class="<?= ViewHelpers::activeClass('/usuarios') ?>">
                <?= ViewHelpers::linkTo('/usuarios', '<i class="fa fa-users"></i> Usuários Cadastrados') ?>
              </li>

              <li role="separator" class="divider"></li>
              <li>
                <?= ViewHelpers::linkTo('/logout', '<i class="fa fa-sign-out" aria-hidden="true"></i> Logout') ?>
              </li>
            </ul>
          </li>
        </ul>

        <!--  SE NÃO ESTIVER LOGADO -->
      <?php else: ?>
        <ul class="nav navbar-nav navbar-right">
          <li class="<?= ViewHelpers::activeClass('/criar-conta') ?>">
            <?= ViewHelpers::linkTo('/criar-conta', '<i class="fa fa-user-plus"></i> Criar Conta') ?>
          </li>

          <li class="<?= ViewHelpers::activeClass('/login') ?>">
            <?= ViewHelpers::linkTo('/login','<i class="fa fa-sign-in"></i> Login'); ?>
          </li>
        </ul>
      <?php endif ?>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
