<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><?= ViewHelpers::fullTitle(@$this->pageTitle) ?></title>
  <?= ViewHelpers::stylesheetIncludeTag('/bootstrap/css/bootstrap.min.css',
                                        '/animate.css-master/animate.css',
                                        'application.css',
                                        '/fonts/font-awesome/css/font-awesome.min.css'); ?>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

  <?php require '_navbar.phtml'; ?>

  <div class="container">
    <div class="row">
      <?php if (SessionHelpers::isLoggedIn()): ?>
        <div class="col-md-12 animated fadeInUp">
        <?php else: ?>
          <div class="col-md-3"></div>
          <div class="col-md-6 animated flipInX">
          <?php endif ?>

          <div class="center-container">
            <?php require '_flash_messages.phtml' ?>
            <?php require $view; ?>
          </div>
        </div> <!-- col-md-X -->
      </div> <!-- row -->
    </div> <!-- container -->

    <?= ViewHelpers::javascriptIncludeTag('jquery-1.11.3.min.js',
                                          '/bootstrap/js/bootstrap.min.js',
                                          '/animate.css-master/dropdown.js',
                                          'jquery.autocomplete.min.js',
                                          'application.js',
                                          'jquery.maskedinput.min.js') ?>
  </body>
  </html>
