<form role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="POST">
  <div class="row">

    <div class="col-md-6">
      <div class="form-group input-group <?= $this->category->getErrors('name') ? 'has-error' : '' ?>">
        <span class="input-group-addon">Nome</span>
        <input type="text" class="form-control" name="category[name]" value="<?= $this->category->getName() ?>"
        id="category_name" placeholder="Categoria" autofocus>
      </div>
      <p class="help-block"><?= $this->category->getErrors('name') ?></p>
    </div>
  </div>

  <button type="submit" class="btn btn-primary"> <?= $this->submit ?></button>
</form>
