<section class="page-header">
  <div class="row">
    <div class="col-md-12">
      <?= ViewHelpers::linkTo("/categorias/{$this->category->getId()}", '<i class="fa fa-arrow-left"></i>', "class='btn btn-primary'"); ?>
      <h4 class="pull-right"><i class="fa fa-pencil-square-o"></i> Editando: <small> Categoria ID: <?= $this->category->getId() ?></small></h4>
    </div>
  </div>
</section>

<section>
  <?php require '_form.phtml'; ?>
</section>
