
<section class="page-header">

  <?= ViewHelpers::linkTo('/categorias/novo', '<i class="fa fa-plus"></i> Nova Categoria', "class='btn btn-primary'"); ?>

  <form class="form-inline pull-right" role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="GET">
    <div class="input-group">
      <input type="text" class="form-control" name="search" id="search_field" placeholder="Pesquisar Categoria" value="<?= $this->value ?>">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
</section>

<section>
  <div class="text-center">
    <h3> <i class="fa fa-tags fa-2x"></i> Categorias<small> <?= $this->subtitle ?></small> </h3>
  </div>

  <table class="table table-hover table-bordered text-center ">
    <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Nome <i class="fa fa-sort-desc"></i></th>
        <th class="text-center">Detalhes</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->categories as $category): ?>
        <tr>
          <td><?= $category->getId(); ?></td>
          <td><?= ViewHelpers::truncate($category->getName(), 25); ?></td>
          <td><?= ViewHelpers::linkTo("/categorias/{$category->getId()}", '<i class="fa fa-file-text-o"></i>') ?></td>
        </tr>
        <?php endForeach; ?>
      </tbody>
    </table>
  </section>
