<section class="page-header">
  <?= ViewHelpers::linkTo('/produtos', '<i class="fa fa-arrow-left"></i>', "class='btn btn-primary'"); ?>

  <?= ViewHelpers::linkTo("/produtos/{$this->product->getId()}/editar", '<i class="fa fa-pencil-square-o"></i> Editar', "class='btn btn-primary'") ?>
  <?= ViewHelpers::linkTo("/produtos/{$this->product->getId()}/deletar", '<i class="fa fa-times "></i> Deletar', "class='btn btn-primary'") ?>
  <h4 class="pull-right"><i class="fa fa-file-text-o"></i> Detalhes: <small> Produto ID: <?= $this->product->getId() ?></small></h4>
</section>

<section>
  <form role="form">
    <div class="form-group input-group">
      <span class="input-group-addon">Nome</span>
      <input type="text" class="form-control" value="<?= $this->product->getName() ?>"
      id="product_name" disabled>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group input-group ">
          <span class="input-group-addon">Categoria</span>
          <select  class="form-control" id="product_category" disabled>
            <option selected>
              <?= $this->product->getCategory()->getName() ?>
            </option>
          </select>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group input-group">
          <span class="input-group-addon">Unidades em Estoque</span>
          <input type="number" class="form-control" value="<?= $this->product->getAmount() ?>"
          id="product_amount" disabled>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group input-group">
          <span class="input-group-addon">Preço de Venda</span>
          <input type="text" class="form-control" value="<?= ViewHelpers::currencyFormat($this->product->getSellingprice()); ?>"
          id="product_sellingprice" disabled>
        </div>
      </div>
    </div>
  </form>
</section>
